# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170602_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.TextField(default=None, verbose_name=lists.models.List),
        ),
    ]
